#define WINDOW_TITLE "Slot Machine Game"
#define WINDOW_WIDTH 400
#define WINDOW_HEIGHT 400
#define INITIAL_MONEY 5000
#define WITHDRAW_MONEY 500
#define GAIN_MONEY 4000
#define DEFAULT_VOLUME 60
#define DEFAULT_FPS 40